### ISSUE TITLE
Deprecation warning with latest version of AA

### ISSUE THREAD

**Issue by kofronpi** [Papercloud/active_admin_csv_import#11]
When tracking master for ActiveAdmin 1.0.0pre, a deprecation warning is thrown when starting the app:

```WARN -- : DEPRECATION WARNING: Active Admin: using `action_item` without a name is deprecated! Use `action_item(:edit)`. (called from action_item at /***/.bundle/ruby/2.1.0/bundler/gems/activeadmin-77adc9d56b41/lib/active_admin/dsl.rb:92)```

Maybe it's a good time to update dependencies and test against Rails 4.1 plus the latest version of AA?

**Comment by BRZInc** [comment]
I also have these warnings, when I'm running my rspec

**Comment by felipecamposclarke** [comment]
@BRZInc +1

**Comment by tspacek** [comment]
Fixed in v2.0.0
